name: OCI Image build and push

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'latest'

jobs:
  build-oci-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract tag name
        id: meta
        run: |
          # 'release'イベントの場合は、リリースタグを使用し、そうでない場合は手動入力されたタグを使用する
          if [[ ${{ github.event_name }} == "release" ]]; then
            TAG=$(basename ${{ github.ref_name }})
          else
            TAG="${{ inputs.tag }}"
          fi
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: shuheikawamura243/quacklyzer:${{ steps.meta.outputs.tag }}
