name: ESLint

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/eslint.yaml'
      - '**.md'
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - name: Download dependencies
        run: npm install
      - name: ESLint
        run: npm run lint
